name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Getir
        uses: actions/checkout@v4

      - name: Cypress Kur ve Calistir
        # Bu komut her şeyi sıfırdan kurar
        uses: cypress-io/github-action@v6
