name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Getir
        uses: actions/checkout@v4

      - name: Bagimliliklari Kur
        run: npm install

      - name: Cypress Testlerini Calistir
        uses: cypress-io/github-action@v6
        with:
          install: false
