name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Getir
        uses: actions/checkout@v4

      - name: Her Seyi Kur
        run: npm install

      - name: Testleri Baslat
        uses: cypress-io/github-action@v6
        with:
          install: false
          config: supportFile=false
